### ISSUE TITLE
Execute as 

### ISSUE THREAD

**Issue by Levertion** [MrYurihi/mcfunction#1]
1. Create a minecraft13 grammared file  
2. Type in `execute as`
3. Press space
4. Get error

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [mcfunction](https://github.com/MrYurihi/mcfunction) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'include' of undefined

```
At C:\Users\Levertion\.atom\packages\mcfunction\lib\provider.js:143

TypeError: Cannot read property 'include' of undefined
    at Object.runCycle (/packages/mcfunction/lib/provider.js:143:11)
    at Object.runCycle (/packages/mcfunction/lib/provider.js:83:25)
    at Object.getCommandStop (/packages/mcfunction/lib/provider.js:56:15)
    at Object.getSuggestions (/packages/mcfunction/lib/provider.js:168:20)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -0:51 core:move-up (input.hidden-input)
     -0:50.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.6.0 core:move-down (input.hidden-input)
     -0:49.2.0 core:move-up (input.hidden-input)
     -0:49.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:48.8.0 core:move-down (input.hidden-input)
  3x -0:47.3.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:15.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  6x -0:14.5.0 core:select-right (input.hidden-input)
  2x -0:11 core:backspace (input.hidden-input)
  2x -0:10.1.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:07.3.0 core:backspace (input.hidden-input)
     -0:06.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:06.6.0 snippets:expand (input.hidden-input)
     -0:06.6.0 editor:indent (input.hidden-input)
  4x -0:06.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
file-icons 2.1.11 
git-log 0.4.1 
git-tabs 0.2.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
language-htaccess 0.1.1 
language-liquid 0.6.0 
language-minecraft-function 0.0.0 
mcfunction 0.4.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.2 
package-cop 0.2.10 
pigments 0.40.2 
Remote-FTP 1.1.3 
```

**Comment by Levertion** [comment]
Note that language-minecraft-function is my take on syntax highlighting, which is nowhere near done and I think I'm going to use yours anyway.
